version: '3'

services:
    cash_server:
        image: cash_server
        build:
            context: ./servers/cash
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        depends_on:
            - cash_db

    cash_db:
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=cash
            - PGDATA=/var/lib/postgresql/data
        volumes:
            - ./servers/cash/pg_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    bank_server:
        image: bank_server
        build:
            context: ./servers/bank
            dockerfile: Dockerfile
        volumes:
            - ./servers/bank:/app
        ports:
            - "8081:8081"
        depends_on:
            - bank_db

    bank_db:
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=bank
            - PGDATA=/var/lib/postgresql/data
        volumes:
            - ./servers/bank/pg_data:/var/lib/postgresql/data
        ports:
            - "5433:5432"

    github_runner:
        image: github_runner
        build:
            context: .github/runner
            dockerfile: Dockerfile
        environment:
            - TOKEN=ASYVSAZU6K2OIFFKU32JPJ3FN4LDQ
            - RUNNER_ALLOW_RUNASROOT=1
