version: '3'

services:
  cash_manager_server:
    image: cash_manager_server
    container_name: cash_manager_server
    build:
      context: ./servers/cash
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - cash_manager_db

  cash_manager_db:
    image: postgres:latest
    container_name: cash_manager_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cash_manager_db
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./servers/cash/pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bank_server:
    image: bank_server
    container_name: bank_server
    build:
      context: ./servers/bank
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - bank_server_db

  bank_server_db:
    image: postgres:latest
    container_name: bank_server_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bank_server_db
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./servers/bank/pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
