name: Deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      # - name: Setup Maven
      #   uses: stCarolas/setup-maven@4.4
      #   with:
      #     maven-version: '4.4.0'

      - name: Unit Tests
        run: mvn clean package
      
      - name: Rename the artifact
        run: cp servers/bank/target/*.jar bank/bank-${{ github.sha }}.jar
      
      - name: Save the artifact
        uses: actions/upload-artifact@master
        with:
          name: bank-server
          path: bank/bank-${{ github.sha }}.jar
      
fake-deploy:
    runs-on: ubuntu-latest
    needs: run-unit-tests
    steps:
      - name: Get the artifact
        uses: actions/download-artifact@master
        with:
          name: bank-server
      
      - name: Fake Deploy
        run: ls -l bank/*.jar
