# run my java spring boot tests
name: tests-action

on:
  push:
    branches-ignore:
      - main

jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Change directory to the project
        run: cd servers/bank

      - name: All the Tests and Coverage Checks
        run: mvn clean install

